# Generated by AloCentra Batch 1 changes.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_restructure_programs_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='program_type',
            field=models.CharField(default='UG', max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.CharField(
                choices=[
                    ('core', 'Core'),
                    ('lab', 'Lab'),
                    ('sec', 'SEC'),
                    ('oe', 'OE'),
                    ('aecc', 'AECC'),
                ],
                default='core',
                max_length=10,
            ),
        ),
    ]

