# Generated by Django 4.2.9 on 2026-03-29 16:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("timetable", "0003_program_type_and_course_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={"ordering": ["program_id", "semester", "code"]},
        ),
        migrations.AlterField(
            model_name="course",
            name="semester",
            field=models.PositiveSmallIntegerField(),
        ),
    ]
