# Generated by Django 4.2.9 on 2026-04-19 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("timetable", "0005_program_type_phd_datafix"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimetableDateConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("exam_time", models.TimeField(blank=True, null=True)),
                (
                    "timetable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="date_configs",
                        to="timetable.examtimetable",
                    ),
                ),
            ],
            options={
                "unique_together": {("timetable", "date")},
            },
        ),
    ]
