# Generated by Django 6.0.4 on 2026-04-19 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0006_timetabledateconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetabledateconfig',
            name='duration_hours',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timetabledateconfig',
            name='duration_minutes',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
