# Generated by AloCentra Batch 1 changes.

import re
from django.db import migrations, models


def _parse_duration_to_hours_minutes(raw: str) -> tuple[int, int]:
    if raw is None:
        return (0, 0)
    s = str(raw).strip().lower()
    if not s:
        return (0, 0)

    # Plain integer -> hours
    if s.isdigit():
        return (max(int(s), 0), 0)

    # "H:M"
    m = re.match(r'^\s*(\d+)\s*:\s*(\d+)\s*$', s)
    if m:
        h = int(m.group(1))
        mi = int(m.group(2))
        if mi >= 60:
            h += mi // 60
            mi = mi % 60
        return (max(h, 0), max(mi, 0))

    # "2 hours", "2 hr", "2h", "2hours"
    m = re.search(r'(\d+)\s*(h|hr|hrs|hour|hours)\b', s)
    if m:
        return (max(int(m.group(1)), 0), 0)

    # "90 min", "90 minutes"
    m = re.search(r'(\d+)\s*(m|min|mins|minute|minutes)\b', s)
    if m:
        total_min = max(int(m.group(1)), 0)
        return (total_min // 60, total_min % 60)

    return (0, 0)


def forwards_copy_duration(apps, schema_editor):
    ExamType = apps.get_model('duty', 'ExamType')
    for et in ExamType.objects.all():
        h, m = _parse_duration_to_hours_minutes(getattr(et, 'duration_text', ''))
        et.duration_hours = h
        et.duration_minutes = m
        et.save(update_fields=['duration_hours', 'duration_minutes'])


def reverse_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('duty', '0002_dutyassignment_drop_examtype_shortname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examtype',
            old_name='duration_hours',
            new_name='duration_text',
        ),
        migrations.AddField(
            model_name='examtype',
            name='duration_hours',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='examtype',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='examtype',
            name='exam_program_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.RunPython(forwards_copy_duration, reverse_noop),
        migrations.RemoveField(
            model_name='examtype',
            name='duration_text',
        ),
    ]

