# Generated by Django 4.2.9 on 2026-03-29 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("duty", "0003_examtype_duration_split_and_program_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dutyassignment",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="duty.dutysession",
            ),
        ),
    ]
