# Generated by Django 4.2.29 on 2026-03-31 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('duty', '0005_dutysession_timetable'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='examtype',
            unique_together={('name', 'exam_program_type', 'duration_hours', 'duration_minutes')},
        ),
    ]
