# Generated by Django 4.2.9 on 2026-04-19 12:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("duty", "0006_alter_examtype_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="examtype",
            name="default_start_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
