# Generated by Django 6.0.4 on 2026-04-19 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duty', '0007_examtype_default_start_time'),
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DutyReserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.faculty')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserves', to='duty.dutysession')),
            ],
            options={
                'ordering': ['added_at'],
                'unique_together': {('session', 'faculty')},
            },
        ),
    ]
